

name: Deploy to Snowflake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: 
    environment: production 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
